services:
  database:
    container_name: database
    hostname: database
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080" # http://localhost:1080
      - "1025:1025"
  storage:
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=local
      - MINIO_ROOT_PASSWORD=12345678
      - MINIO_DEFAULT_BUCKETS=project-s
    volumes:
      - 'storage:/data'
    command: ["server", "/data"]

volumes:
  storage:
    driver: local
  # https://hub.docker.com/_/redis/