services:
  # TODO: add apps
  core:
    image: node:latest
    depends_on:
      - database
      - maildev
      - storage
      # - redis
    ports:
      - 8080:8080
    volumes:
      - ".:/usr/project-s"
    command: >
      bash -c "cd ./usr/project-s/ && 
      npm install --workspace=applications/core --loglevel verbose && 
      cd ./applications/core &&
      npm run start:dev"
    
  # backoffice:
  # platform:

  database:
    hostname: database
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080" # http://localhost:1080
      - "1025:1025"
  storage:
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001' # http://localhost:9001
    environment:
      - MINIO_ROOT_USER=local
      - MINIO_ROOT_PASSWORD=12345678
    volumes:
      - 'storage:/data'
    command: ["server", "/data", "--console-address", ":9001"]

  # https://hub.docker.com/_/redis/
  # redis
volumes:
  storage:
    driver: local
    

  