services:
  database:
    container_name: database
    hostname: database
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=local
      - POSTGRES_PASSWORD=local
  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"