export default {
  AuthService: Symbol.for('AuthService'),
  AccessPlanRepository: Symbol.for('AccessPlanRepository'),
  AuthTokenManager: Symbol.for('AuthTokenManager'),
  Encryptor: Symbol.for('Encryptor'),
  PolicyRepository: Symbol.for('PolicyRepository'),
  UserRepository: Symbol.for('UserRepository'),
  AuthMiddleware: Symbol.for('AuthMiddleware'),
  CatalogService: Symbol.for('CatalogService'),
  CatalogRepository: Symbol.for('CatalogRepository'),
  Mediator: Symbol.for('Mediator'),
  TenantExistsCommandHandler: Symbol.for('TenantExistsCommandHandler'),
  EmailService: Symbol.for('EmailService'),
  VerificationCodeRepository: Symbol.for('VerificationCodeRepository'),
};