name: Continuous Integration

on: push

jobs:
  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [latest]
        redis-version: [7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker compose
        run: docker compose up --build -d

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Deps & Tests
        run: npm ci
        run: npm run test:cov