name: Continuous Integration

on: push

jobs:
  core-coverage:
    name: Core Coverage
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [latest]
        redis-version: [7]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker compose
        run: docker compose up database redis maildev storage --build -d

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Deps
        run: npm ci

      - name: Run Database Migrations
        run: npm run -w applications/core db:migrate up

      - name: Test Coverage
        run: npm run -w applications/core test:cov