name: Continuous Integration

on:
  workflow_dispatch:
    branches: [ main ]

jobs:
  lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install Deps
        run: npm ci
      - name: Linting
        run: npm run -w applications/core lint
  
  coverage:
    name: Core Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker compose
        run: docker compose up database redis maildev storage --build -d

      - name: Use Node.js latest
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Install Deps
        run: npm ci

      - name: Run Database Migrations
        run: npm run -w applications/core test:db:migrate up

      - name: Test Coverage
        run: npm run -w applications/core test:cov